services:
  - type: web
    name: diet-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    runtime: python
    autoDeploy: true
    branch: main
